on:
  push:
    branches:
    - main

name: latest build

jobs:
  build:
    name: Build project
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build
